export const API_URL = process.env.NEXT_PUBLIC_API_URL;
export const GITLAB_CLIENT_ID = process.env.NEXT_PUBLIC_GITLAB_CLIENT_ID;
export const GITHUB_CLIENT_ID = process.env.NEXT_PUBLIC_GITHUB_CLIENT_ID;
export const BITBUCKET_CLIENT_ID = process.env.NEXT_PUBLIC_BITBUCKET_CLIENT_ID;
export const URL_GITLAB = process.env.NEXT_PUBLIC_URL_GITLAB;
export const URL_GITHUB = process.env.NEXT_PUBLIC_URL_GITHUB;
export const URL_BITBUCKET = process.env.NEXT_PUBLIC_URL_BITBUCKET;
export const WEBAPP_URL = process.env.NEXT_PUBLIC_WEBAPP_URL;

export default {
  API_URL,
  WEBAPP_URL,
  GITLAB_CLIENT_ID,
  GITHUB_CLIENT_ID,
  BITBUCKET_CLIENT_ID,
  URL_GITLAB,
  URL_GITHUB,
  URL_BITBUCKET,
};
